version: 2.0

id: renovate-config

about:
  title: renovate-config
  description: Global config for Renovate dependency updater

contacts:
  - type: Project Manager
    name: Natasha Lander
    email: natasha.lander@telus.com
    github: NatashaLander
  - type: developer
    name: Mauricio Mercado
    email: mauricio.mercado@telus.com
    github: maumercado
  - type: developer
    name: Samantha Vale
    email: samantha.bezerra_vale@telus.com
    github: karlasamantha
  - type: developer
    name: Ruxandra Fediuc
    email: ruxandra.fediuc@telus.com
    github: ruxandrafed
  - type: developer
    name: Kyle Spaans
    email: kyle.spaans@telus.com
    github: kspaans

environments:
  - type: git
    title: Source Code
    uri: https://github.com/telus/renovate-config
  - type: npm
    title: NPM Package
    uri: https://www.npmjs.com/package/@telus/renovate-config
